on:
  push

name: Quarto Netlify Publish
# with code from r-lib/actions (CC0)

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install dependencies
        run: |
          echo "::group::Install dependencies"
          if which sudo >/dev/null; then SUDO="sudo -E --preserve-env=PATH env"; else SUDO=""; fi
          R_LIB_PATH="/tmp/lib"
          $SUDO R -q -e 'dir.create(Sys.getenv("R_LIB_PATH"), recursive = TRUE, showWarnings = FALSE)'
          $SUDO R -q -e 'install.packages(c("rmarkdown", "tidyverse", "janitor", "dplyr", "Matrix", "ggplot2", lib = Sys.getenv("R_LIB_PATH")))'
          echo "::endgroup::"
        shell: bash

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
